---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jellyfin
  - radarr
  - sonarr
  - lidarr
  - prowlarr
  - flaresolverr
  # - transmission
  - qbittorrent
  - cleanuparr
  - calibre-web-automated
  - calibre-web-automated-downloader
