---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jellyfin
  - radarr
  - sonarr
  - lidarr
  - lidatube
  - prowlarr
  - flaresolverr
  - qbittorrent
  - calibre-web-automated
  - shelfmark
  - seerr
