apiVersion: batch/v1
kind: CronJob
metadata:
  name: awpa2
  namespace: projects
spec:
  schedule: "0 7 * * *"  # Every day at 7am
  # schedule: "* * * * *"  # test
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              image: maneeshwije/awpa:latest
              command: ["bash", "-c"]
              args:
                - |
                  set -e
                  node dist/scrape.js
                  echo "Job finished â€” sleeping for debugging..."
                  sleep 3600
              env:
                - name: GMAIL_USER
                  valueFrom:
                    secretKeyRef:
                      name: awpa2-secrets
                      key: GMAIL_USER
                - name: TO_GMAIL_USER
                  valueFrom:
                    secretKeyRef:
                      name: awpa2-secrets
                      key: TO_GMAIL_USER
                - name: GMAIL_PASS
                  valueFrom:
                    secretKeyRef:
                      name: awpa2-secrets
                      key: GMAIL_PASS
                - name: URL
                  valueFrom:
                    secretKeyRef:
                      name: awpa2-secrets
                      key: URL
              volumeMounts:
                - name: amazon-session
                  mountPath: /app/amazon.json
                  subPath: amazon.json
          volumes:
            - name: amazon-session
              secret:
                secretName: awpa2-secrets
