apiVersion: v1
kind: Secret
metadata:
    name: awpa2-secrets
    namespace: projects
stringData:
    GMAIL_USER: ENC[AES256_GCM,data:QP396wRaiireLHGbqyHi/BJFVQ==,iv:OrQXPl08KA3h6foc0wEsI4WEoQVdkbryReJEiHcyfgI=,tag:8Ill90rko9aA313x9XJacQ==,type:str]
    GMAIL_PASS: ENC[AES256_GCM,data:YSzaXie5UBeS4eVHhketJXy/Uw==,iv:YqWE5Sw5QENRJrT2d7++DbksF0S1juHLtgPHRi79Wj8=,tag:as8zlFnHdg6UydU04VEzKA==,type:str]
    URL: ENC[AES256_GCM,data:lpHoS2RfuN48PdFiub/P7Hv8UZNximxF5JM2s3BbTu3RSJKJmVWK/whL6im4VIEWFSGdRYIXfUuWyHKj6Uhed6VDb52fEzfmyY75,iv:Je/BGBMGZRQKGmZWyXfzy94lZmLZnaGVMC7pO1nJ6DM=,tag:JfwopMyE+ms29R6zYCVfpw==,type:str]
sops:
    lastmodified: "2026-01-02T01:44:07Z"
    mac: ENC[AES256_GCM,data:KP3qnNms7Ip+aKuRg7AOQ11Y7BT6/vkqNkro0ehTd2OxDewik2SoXADr1amK2VNGMjpVgLiEHUqCH4fVzXmq4s1GXzRtd3Dy6wovlRMqyOk9o4bQqsAEK9rIJ/RJzdWX6aW1GgS+bRKNciVAmGFV887/jp6hjIV6Go1E8f1eHl8=,iv:c13Nc22+z6DFTYzcQEaK32FcBTC88jH7HjxIt2MOtB4=,tag:k/lLZHg4rmffyzoQiYxDOQ==,type:str]
    pgp:
        - created_at: "2026-01-02T01:44:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyR7mfh0bsINAQ/9G8YU1CntqdDViMmXzEGxkuaVWlkFqzSIG7QFlNrN4PVg
            VUIsci7rtWrcrUnGqqfg0LLuKAhE68aLcB2cez6WnYc6W82An92zuI1bfzUHlPDB
            sD5YvuSdf2/cGE4DTDXVwIFv1mEVeCoUZ+hCtIAEySITTVgio6X8hcI9xNQ9/6Cz
            hmQ7eIkBRItTRIShMZWRvX6RedJ5eNAZtdRaHgJvfE5r7L/XtUrzyIs6Lqh7+dGY
            hueTxjJ23mkgszlBXR8Hua6yFOamTLNvHyoWr03/CQUMPwjXJNp3Pt2GLkwIgwCa
            BGabIb6Rdxb4h2/re69DD5HYRtQXt6z0M1wqacsyaR4qDm62MiYgeRJC/w0c50jL
            sWIwSsxgro6PyQWdVk3ihQH217A09Io9fpFKMUfqlGv7Bw/2yP/djbGtq5rqsaeg
            X8BpirtXQ/UFbVeRywFZkb5f0bFATqnCHpthiP5gFfULPTbKDaI4pjurtPl2Z5wF
            ck2fyzOKif+C5oYfKhDDupuBfQG0VF0E0KMvi6VRxEktWm1lO10uqNl5QrAWaeSx
            z1v45xG7/3dPL0lq2VW9E9+xit6bOZrUP3OgRUQYRlaA2WAw3dLVqB/P/lNsUtuy
            Y9UMjllkzE9vcyrBH1mgmJ/QJJ/OQHvfOBAAb54SHaPx0QR8FooRji6Z2FbUaPbS
            XgE8r/OI39fiDBXjTGz8blzQ7DJUb5ynxP91iX8gHGARMF4ZJ7nGBPrFI1ChJvRS
            cMIh+rnfKMf4ojaNbZvduBGeTE0Al/L1mPtP1PWkDqcuV+K4xC3MqQHVkVN7GAU=
            =A8mL
            -----END PGP MESSAGE-----
          fp: C727E1154C6047ED0D0F6F496354D6BDC77CF302
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
