---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: awpa
  namespace: projects
spec:
  schedule: "0 7,22 * * *"  # Every day at 7am and 10pm
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              image: maneeshwije/awpa:latest
              env:
                - name: SENDER_EMAIL
                  valueFrom:
                    secretKeyRef:
                      name: awpa-secrets
                      key: SENDER_EMAIL
                - name: RECEIVER_EMAIL
                  valueFrom:
                    secretKeyRef:
                      name: awpa-secrets
                      key: RECEIVER_EMAIL
                - name: SENDER_PASS
                  valueFrom:
                    secretKeyRef:
                      name: awpa-secrets
                      key: SENDER_PASS
                - name: URL
                  valueFrom:
                    secretKeyRef:
                      name: awpa-secrets
                      key: URL
                - name: DELTA
                  valueFrom:
                    secretKeyRef:
                      name: awpa-secrets
                      key: DELTA
                - name: DATA_PATH
                  valueFrom:
                    secretKeyRef:
                      name: awpa-secrets
                      key: DATA_PATH
              volumeMounts:
                - name: amazon-session
                  mountPath: /app/amazon.json
                  subPath: amazon.json

                - name: data
                  mountPath: /data
          volumes:
            - name: amazon-session
              secret:
                secretName: awpa-secrets
            - name: data
              persistentVolumeClaim:
                claimName: awpa-data
