apiVersion: v1
kind: Secret
metadata:
    name: markdown-edit-secrets
    namespace: projects
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:tVH7lITli46JGCC6un8Slnsc4fiUOAxlB6N7TiZU+X8e11dl6/pGj3d1B5XKH0cR2s/vcAGo8IlHEtfQd3BcE135gn0eMJmU3Vjpx7apevNxL2QWl2c9d/H7DKWPMqyXeB/AhiLoTAgE,iv:Gkz4OZ3T4YMNge7VctBzOS4BKZLH7PzrT3+nXq+1eGk=,tag:0vGlWyfZLL5U6ip3vOD7Tw==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:2w1nxxCbh5IAVlYrILzWSzckHX1Pkq+VJdx1dgywVpbLEOP5NtY5R1NG7gFQ2rsQSIEfkYOyTe7ZgBePm/JYn8aJ6vwj6uzZ,iv:C7nKGEJXAfmENg0h9PwEK4lt46jO9ZojaMg7Exx6TqA=,tag:OXPiyVzCjK4ObjcZc8lajg==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:N7a7PHHUKin1XVVpBeGT72l9pnx/2rop8uUzX1FEznP18Wo=,iv:0fo6U8wl3M4hs6QIEFLN/1oCTBcwF/teAgRORIevdNA=,tag:BHlPmUu/Xnq/p2w+JXjagA==,type:str]
    BASE_URL: ENC[AES256_GCM,data:+7Z8XPvy2wxf3ApsrHLkNsyes1o3M34k9jtLdktWdpQ=,iv:MTloa1F9XtG3lHbHQr1PSY5RxJjQAD0+en7jQQLFZF8=,tag:22tLixDanzEL9c7CUJcX2g==,type:str]
    CLIENT_URL: ENC[AES256_GCM,data:AVs3vRYGQt8Mg55XCk704V42g//Pn29kfol2WEJtDwY=,iv:VUVIuxOXGWue1YZFA2yvU6Kcm3kvY/llq3sE41wcN18=,tag:MxWy9U7knjuABTioh0t2qg==,type:str]
sops:
    lastmodified: "2025-11-30T17:35:12Z"
    mac: ENC[AES256_GCM,data:nyD5PUuJr8e8IrOBt7Zospl52bY30Xl19gLENbjgUqanf5q19j6dGqB+NOKmrJ6Z/ElBKWKXiakVinBPhv1V/LMXjJJqsFAz8pGuvUosaOxJH4oNZZG7bYDleKpa6kvBmLIdt1ulg1BQF9iYe/b0qMi6AreEPFsdsR+UB9zIClA=,iv:OEbwkBnOJ4o0VYnd2mmkElFyv0g+XzSrneFt89o8QA8=,tag:ZD4sBfg1mLncb+s1KxGVlg==,type:str]
    pgp:
        - created_at: "2025-02-27T03:17:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyR7mfh0bsINAQ/+Ibw6U6TVi/R24RegeNSy6oe7ad4pILrCHZMf6tI7EudE
            ghU6KlGYbkKyB0c9fqV9BS6Q9Aa9GZLmslo5HD0XEX6jAo6IeHC0UiSS0B10Ou8g
            B0XMaxPGthDOuGn3i0OWyiO7xqT/PqnbSq1E1NSEPENOVFVw+RzKyo/z5DP9EYZk
            t9tubnKLTppFBcagZoCEBoI0oYZ51azDTae5P2BBVSy6vEuJ64fxj+YgKDY+2l+M
            wZHBxVI9q1yLhShvjYOCTYS2GYSZ5wSxOdxGxohNfHCE52jqjhdekuBOyehDwwio
            XffCE/w8G+sxL/fZliyd8vTL5U4iEvGS3kptzkL4x/H2/Cv6cu3b3aCCI5wcBJFA
            YU7KRXyTuIGIFhxctDCPOK63ojRgK8NNmBLAtADZ08S426z7HUV2vYLeh/0XsICF
            IowG/eluILJS1PQdoCY7NmbnN4oJni1+MLXCIEmHfM0MUz24XYj4kGbeK38a4SZ7
            /MDH5vPILJrcxrz0z42fZ8RKf/8nX0J7Bb19L/zQGF4UI1hvs+7AQox4OklijbOq
            86bNUhjYZaunlOK8+qL1DtmXr0vlorjx9q4+cuj+wWvmZmT8BcRK63zDp+QDN1uy
            n5ZTIQ+77ODO83Bpp1XGiidyp92xz5HmuYHzLNePvL3qgdvm0pYznVIzXD3ORSjS
            XgHuhx8z+1sN9uL2ZnwcAb35O5h1igP7lAIERlcKvSr57APi063cmRpQbDXj40IG
            LuHPY20C7xBmuQOzNil96ln8ryVpOIik0z9W9sfWO9FITpJJSioOQoQ1pv4qSS4=
            =0a8T
            -----END PGP MESSAGE-----
          fp: C727E1154C6047ED0D0F6F496354D6BDC77CF302
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
